### ISSUE TITLE
Error: Class 'Owner' not found --- pathing issues with permissions.php rules

### ISSUE THREAD

**Issue by alexlambson** [CakeDC/users#442]
When using 

`use CakeDC\Users\Auth\Rules\Owner;`

and 

```
[
    'role' => 'owner',
    'controller' => 'Locations',
    'action' => ['view', 'edit', 'index'],
    'allowed' => new Owner([
        'table' => 'UsersLocations',
        'id' => 'location_id',
                'ownerForeignKey' => 'user_id'
        ]),
],
```

I get the error:

> Error: Class 'Owner' not found 
> File C:\xampp\htdocs\race-day\config\permissions.php 
> Line: 82

However, it will work if I remove the "use" statement and put the path in front of "Owner" like so

`new CakeDC\Users\Auth\Rules\Owner`

I am also using a rule that extends AbstractRule, but I cannot get it to work unless I put it at the top of permissions.php.

**Comment by steinkel** [comment]
Please check you have an updated version of the plugin, I've just did a quick test locally with the following file

```
<?php

use Cake\Network\Request;
use Cake\ORM\TableRegistry;
use Cake\Utility\Hash;
use CakeDC\Users\Auth\Rules\Owner;

/*
 * This is a quick roles-permissions implementation
 * Rules are evaluated top-down, first matching rule will apply
 * Each line define
 * 'role-name' =>
 *      [
 *          'plugin', (default = null)
 *          'controller',
 *          'action',
 *          'allowed' (default = true)
 *      ]
 * You could use '*' to match anything
 */

return [
    'Users.SimpleRbac.Permissions' => [
        [
            'role' => '*',
            'plugin' => 'Users',
            'controller' => '*',
            'action' => '*',
        ],
        [
            'role' => 'user',
            'plugin' => 'Users',
            'controller' => 'Users',
            'action' => ['register', 'edit', 'view'],
        ],
        [
            'role' => 'user',
            'plugin' => 'Users',
            'controller' => 'Users',
            'action' => '*',
            'allowed' => false,
        ],
        [
            'role' => ['user'],
            'controller' => ['Pages'],
            'action' => ['other', 'display'],
            'allowed' => true,
        ],
        //allow access to posts read/add
        [
            'role' => ['user'],
            'controller' => ['Posts'],
            'action' => ['index', 'view', 'add'],
        ],
        //allow edit my posts (ownership)
        [
            'role' => ['user'],
            'controller' => ['Posts'],
            'action' => ['edit', 'delete'],
            'allowed' => new Owner()
        ],
        //view myself
        [
            'role' => ['user'],
            'controller' => ['MyUsers'],
            'action' => ['view'],
            'allowed' => function (array $user, $role, Request $request) {
                $id = Hash::get($request->params, 'pass.0');
                $userId = Hash::get($user, 'id');
                return $id === $userId;
            }
        ],
    ]];
```

**Comment by alexlambson** [comment]
I will test it tomorrow (thursday)

**Comment by alexlambson** [comment]
It's fixed in the latest version.

**Comment by rzelnik** [comment]
I have the latest version of CakeDC/users and the "Error: Class 'Owner' not found" still occurs. When I change the rule to this:

`        [
            'role' => ['user'],
            'controller' => 'Articles',
            'action' => ['edit', 'delete'],
            'allowed' => new \CakeDC\Auth\Rbac\Rules\Owner(),
        ],`

The error message disappear, but I still can't edit the owner's content - it shows a flash message:

> You are not authorized to access that location.
